### ISSUE TITLE
Not able to add Synology to Homey

### ISSUE THREAD

**Issue by knakkerhenk** [jordenc/com.synology.surveillance#5] opened 2018-04-08 13:37 UTC
Hi,

I'm not able to add my Synology NAS (DS213+ - DSM 6.1.6-1526) to my Homey (1.5.9), after filling in the needed information when I click on "save information"  nothing happens... Anybody any clue why?
![homey-add_synology](https://user-images.githubusercontent.com/38183909/38468169-a9fcb7c6-3b42-11e8-86d9-e1999f74afd7.png)

**Comment by Cokeisit** [comment] 2018-06-15 13:16
I got the same error. Using DS214Play with DSM 6.1.7-15284.

**Comment by jordenc** [comment] 2018-06-26 12:48
Please try to run it as a developer using the command line interface. Let me know what the error is at the point that you click the "Gegevens opslaan" button.

**Comment by depeej** [comment] 2018-07-20 07:43
The error doesn't seems to be solved yet. Any way to get this app running?

**Comment by jordenc** [comment] 2018-07-20 08:15
If you can try running it as a developer via the command line and send me the logs (make sure to remove your password if it is in the logs), I will have a look at what the problem is.

**Comment by depeej** [comment] 2018-07-20 08:19
Hi Jordenc, could you explain me how I have to do that? Thanks!

**Comment by jordenc** [comment] 2018-07-20 08:26
The steps are described on https://developer.athom.com/docs/apps/tutorial-Getting%20Started.html and it is step 1, 2, and 3. It requires some technical knowledge, using the commandline on your PC etc.

You have to:
1- Install NodeJS on your computer
2- Install the athom package (npm install -g athom-cli)
3- Login to the Athom app

Next, either download https://github.com/jordenc/com.synology.surveillance/archive/master.zip or use git (you might have to install that) to clone:
 git clone https://github.com/jordenc/com.synology.surveillance

cd into the com.synology.surveillance directory and run the app:
 athom app run

Next, go to your Homey in the browser and try to add the Synology. Then go back to your commandline screen and see what it tried to do.

**Comment by depeej** [comment] 2018-07-20 14:42
Hmm I guess that is way to complicated for me. I'm afraid that my system will damage.

**Comment by depeej** [comment] 2018-07-24 13:56
@jordenc: Is there an other way to connect my Foscam IP camera to my Homey? I'd like to receive a snapshot of my IP camera to my iPhone when someone rings my doorbell.

**Comment by 2benl** [comment] 2018-07-24 14:11
You could use the imagegrabber app. I have been using this in the waiting time for the new Synology app.

**Comment by depeej** [comment] 2018-07-25 07:31
@2benl: Thanks a LOT! It works just like it did on Domoticz now, great! Would the Synology app be able to sent the screenshot directly from Homey with a push notification?

**Comment by jordenc** [comment] 2018-07-25 08:01
@depeej No, the Synology basically does the same thing as the ImageGrabber, but using the Synology functionality instead of the camera's functions.
The Synology app also doesn't support the new tokens yet, so you cannot use the screenshot anymore (still have to start on a SDK v2 version so it also supports the same image tokens)

**Comment by depeej** [comment] 2018-07-25 08:33
Thanks :-) Hopefully it will improve in the future. Would be very nice if Homey could sent screenshots itself.

**Comment by jordenc** [comment] 2018-07-25 08:34
Yeah that should be possible. I hope with the new app it will be built in.

For now, Telegram will do :)

**Comment by gijzo** [comment] 2018-09-07 04:51
same here on 216

**Comment by gijzo** [comment] 2018-09-07 05:17
Hi Jordenc

### enablepolling = undefined
Synology Surveillance Station app - got get_devices from front-end, hostname =192.168.178.100
[CMD] Login called
key = api
val = SYNO.API.Auth
key = version
val = 2
key = method
val = Login
key = account
val = admin
key = passwd
val = ********
key = session
val = NodeSynologyAPI503187621
key = format
val = sid
RESPONSE END "{\"error\":{\"code\":400},\"success\":false}\n"
[CMD] List called
key = api
val = SYNO.SurveillanceStation.Camera
key = version
val = 1
key = method
val = List
key = query
val = ALL
key = sid
val = false
RESPONSE END "{\"error\":{\"code\":105},\"success\":false}"
[CMD] Logout called
key = api
val = SYNO.API.Auth
key = version
val = 2
key = method
val = Logout
key = session
val = SurveillanceStation
key = sid
val = false
RESPONSE END "{\"success\":true}\n"



When i press gegevens opslaan this appears in de command line prompt but the screen in the gui wont dissapear. when i click somewhere the commandline prompt says this:


> Synology Surveillance Station - User aborted pairing, or pairing is finished


But the nas wont appear in my devices.
Hope this helps

**Comment by peppelorum** [comment] 2018-09-13 10:17
> You could use the imagegrabber app. I have been using this in the waiting time for the new Synology app.

How do you do this? Care to share your secrets =)

**Comment by jordenc** [comment] 2018-09-27 13:18
Code 400 means "Invalid action". So something is going wrong there. Could have something to do with the requirements (is the user admin allowed to login via the API? No 2factor authorisation required? etc). Or maybe Synology updated something.
Some users reported that using the local IP of their Synology did not work, but using their "global" IP did. I have not tried this myself.

The app ImageGrabber https://apps.athom.com/app/image.grabber can be used if your camera supports snapshotting. It is a lot easier to do than the Synology app.

**Comment by jordenc** [comment] 2019-01-18 12:14
Closing for now.

**Closed as completed by jordenc** 2019-01-18 12:14 UTC
